### ISSUE TITLE
The geo transform does not survive "ElemWise" operations

### ISSUE THREAD

**Issue by caspervdw** [nens/dask-geomodeling#103]
With @pysjon we encountered a situation with a 10x10 m raster and we subtracted a 0.5x0.5 m raster from it. Waterdepth map situation.

The result is a geoblock with no geotransform, so no native cellsize, origin and upper bound, which gives problems with formulating an exact bbox for a download request.

I think you can argue that for any elementwise operation, the smallest resolution (geo transform) should survive. What do you think @arjanverkerk  ?

**Comment by arjanverkerk** [comment]
I wouldn't do this. It depends a lot on the individual use cases. And the properties of the sources are a just one link away.

**Comment by caspervdw** [comment]
In the case the smallest cells fitsprecisely in the larger one (as with our water level + DEM combinations), I think it is conceptually correct to take the smaller one
