### ISSUE TITLE
RuntimeError: PROJ: proj_create_from_database: 

### ISSUE THREAD

**Issue by madiazl** [nens/dask-geomodeling#113]
### Contact Details

Andres.diaz

### Complexity

easy

### Priority

low prio

### What happened?

after installing the package desk-geomodelling I got this error by reproducing a very simple example

### How to Reproduce?

# Update model in Lizard
username = '__key__'
password = ''
headers = {"username": username, "password": password, "Content-Type": "application/json"}

import getpass
import json
import numpy as np
import requests
import simplejson
import os

from dask_geomodeling.raster import *
from dask_geomodeling.geometry import *

# Data inputs are LizardRasterSources. Create a dictionary of layer_name: uuid.
lizard_rasters = {"Svf_skyview": "17179b53-d662-448c-973b-22c71791c1ab",
                  "schaduw_fractie" : "26742b28-6e26-4e32-bbee-913e7db62ad2",
                  "fveg" : "27759a30-ab50-48b0-b595-00ce04e205bf",
                  "landuse_raw": "44ca0ac5-aaa9-4fc9-877c-40649d45a429",
                  "trees_cm_height": "461fbed6-dc5f-4b85-91fe-7b7352cd99b1",
                  "NL_value_0": "84f09e7d-331f-4eba-afd7-d7a7934b01de",
                  "NL_buffer_1": "de741b38-47ac-4ac2-984f-0e92c7b695d4",
                  "land_use_update": "526a9cbd-afbb-427c-a66f-9640b90da8d4",
                  "fveg_update": "c06cae45-8675-4097-9233-336ea539a365"
                 }

# Mimic lizard rasters locally with rasterized wkt polygons
dg_rasters = {}
wkt = "POLYGON((1 2, 2 3, 2 3, 1 2))"                                     
for counter, (raster, uuid) in enumerate(lizard_rasters.items(), 1):
    print(counter,raster,uuid)
    # Use RasterizeWKT locally, replace it later with LizardRasterSource
    # To get unique dummy sources use wkt.replace("1", "{RASTERNUMBER}")
    dg_rasters[raster] = misc.RasterizeWKT(wkt.replace("1", str(counter)), "EPSG:28992")

graph_rasters = {lizard_rasters[k]:list(v.serialize()["graph"].items())[0][1] for k, v in dg_rasters.items()}
locals().update(dg_rasters)

RuntimeError: PROJ: proj_create_from_database: 

### What did you expect and what was the actual result?

I expected dg_rasters object

### Additional info

Anything else you would like to share?

**Comment by caspervdw** [comment]
This is most probably an issue with your local GDAL installation - unrelated to dask-geomodeling.
