### ISSUE TITLE
Add Log and Exp functions

### ISSUE THREAD

**Issue by caspervdw** [nens/dask-geomodeling#67]
Question from customer via @joeriverheijden

**Comment by GeOdin** [comment]
@caspervdw 

Hey Casper :)

Ik weet niet zo goed hoe ik de Geoblocks moet testen.

Zou jij deze nog een keer na willen kijken?
En zou je me begin november een introductie in Geoblocks en het testen ervan willen geven?
(Ik heb begrepen dat je voor die tijd erg druk bent.)

Groetjes,
Madeleine
